"""add_settings_table

Revision ID: 5b02fbe7d939
Revises: 445c80d4983e
Create Date: 2025-11-04 16:05:22.347317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b02fbe7d939'
down_revision: Union[str, None] = '445c80d4983e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False, default='School Copy Manufacturing'),
    sa.Column('company_email', sa.String(), nullable=False, default='info@schoolcopy.com'),
    sa.Column('company_phone', sa.String(), nullable=False, default='+92 300 1234567'),
    sa.Column('company_address', sa.String(), nullable=False, default='123 Business Street, Karachi'),
    sa.Column('currency_code', sa.String(), nullable=False, default='PKR'),
    sa.Column('currency_symbol', sa.String(), nullable=False, default='Rs'),
    sa.Column('timezone', sa.String(), nullable=False, default='Asia/Karachi'),
    sa.Column('date_format', sa.String(), nullable=False, default='DD/MM/YYYY'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###